# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-26 07:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('requirement', models.TextField(null=True)),
                ('starttime', models.DateTimeField()),
                ('duetime', models.DateTimeField()),
                ('submit_limits', models.IntegerField(null=True)),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Assignment_Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=100)),
                ('is_corrected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('credit', models.IntegerField()),
                ('time', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('team_uplimit', models.IntegerField()),
                ('team_downlimit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Course_Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EducationalSystem.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Course_Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EducationalSystem.Course')),
            ],
        ),
        migrations.CreateModel(
            name='EduAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('number', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('path', models.CharField(max_length=100)),
                ('virtual_path', models.CharField(max_length=100)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EducationalSystem.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('number', models.CharField(max_length=10)),
                ('dept', models.CharField(max_length=30)),
                ('grade', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(null=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EducationalSystem.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EducationalSystem.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('number', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_approved', models.BooleanField(default=False)),
                ('reason', models.TextField(null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EducationalSystem.Course')),
                ('manager_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EducationalSystem.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Team_Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.FloatField(null=True)),
                ('comment', models.TextField(null=True)),
                ('submit_times', models.IntegerField(default=0)),
                ('asn_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EducationalSystem.Assignment')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EducationalSystem.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('week', models.IntegerField()),
                ('is_over', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='student_team',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EducationalSystem.Team'),
        ),
        migrations.AddField(
            model_name='student_grade',
            name='team_asn_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EducationalSystem.Team_Assignment'),
        ),
        migrations.AddField(
            model_name='course_teacher',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EducationalSystem.Teacher'),
        ),
        migrations.AddField(
            model_name='course_student',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EducationalSystem.Student'),
        ),
        migrations.AddField(
            model_name='course',
            name='term_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EducationalSystem.Term'),
        ),
        migrations.AddField(
            model_name='assignment_resource',
            name='team_asn_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EducationalSystem.Team_Assignment'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EducationalSystem.Course'),
        ),
    ]
