# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 01:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EducationalSystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=10)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(default='123', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='hour',
            field=models.IntegerField(default=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='other_limit',
            field=models.CharField(default='abc', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eduadmin',
            name='password',
            field=models.CharField(default=123456, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default=123456, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(default=123456, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='duetime',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='starttime',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='assignment_resource',
            name='path',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='chat',
            name='courseid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EducationalSystem.Course'),
        ),
    ]
